name: 🏗️ Build Armbian Trixie WiFi-ON Image

on:
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'Upload ke Release v1.0.0? (true/false)'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build image
        run: |
          chmod +x build-image.sh
          bash build-image.sh

      - name: Upload image to artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-trixie-wifion-image
          path: "*.img.gz"
          retention-days: 30

      - name: Upload to Release
        if: github.event.inputs.upload_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: "*.img.gz"
